/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: UnderRated (https://sketchfab.com/underratedhoodie)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/underrated-hoodie-9b898f0b2be344cfa07ba6b3a83708b4
Title: UnderRated Hoodie
*/

import React, { useRef } from 'react'
import { Center, useGLTF } from '@react-three/drei'
import { OrbitControls } from '@react-three/drei'
import {useFrame} from '@react-three/fiber'

export default function Model(props) {

  const { nodes, materials } = useGLTF('/3DModels/underrated_hoodie/scene-transformed.glb');

  const mesh = useRef(null);

  useFrame((state, delta) => {
    mesh.current.rotation.y += delta;
  })

  return (
    <>
    <directionalLight color = {'#ffffff'} angle={1} position={[3, 3, 0]} />
    <directionalLight color = {'#ffffff'} angle={1} position={[-3, 3, 0]} intensity={0.6}/>
    <directionalLight color = {'#ffffff'} angle={1} position={[0, -3, 3]} intensity={0.3}/>
    <directionalLight color = {'#ffffff'} angle={1} position={[0, -3, -3]} intensity={0.1}/>
    <ambientLight color = {'#1966AF'}/>
    <OrbitControls enableZoom={false} maxPolarAngle={0.5 * Math.PI}/>
    <Center position={[0, 0, 0]}>
    <group {...props} dispose={null} ref = {mesh} scale={6}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.material_4} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.material_4} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.material_4} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.material_4} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.material_8} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.material_9} />
    </group>
    </Center>
    </>
  )
}

useGLTF.preload('/3DModels/underrated_hoodie/scene-transformed.glb')